const { Router } = require("express")
const path = require("path")
const fs = require("fs")
const authRouter = require("./auth-router")
const chatRouter = require("./chat-router")
const usersRouter = require("./users-router")
const meRouter = require("./me-router")
const messageRouter = require("./message-router")
const { Candidate } = require("../models/candidate-model")
const { User } = require("../models/user-model")
const { UserBio } = require("../models/userBio-model")
const { Chat, UserChat } = require("../models/chat-models/chat-model")
const { ChatMessage } = require("../models/chat-models/chat-message-model")
const { Op } = require("sequelize")
const AuthMiddleware = require("../middlewares/auth-middleware")

const router = Router()

router.use("/auth", authRouter)
router.use("/", AuthMiddleware, chatRouter)
router.use("/", AuthMiddleware, usersRouter)
router.use("/", AuthMiddleware, meRouter)
router.use("/messages", AuthMiddleware, messageRouter)

module.exports = router
